import { startOfWeek, formatISO } from "date-fns";
import type { WeekPlan } from "@/types/planner";

const monday = startOfWeek(new Date("2026-05-10T12:00:00"), { weekStartsOn: 1 });
const weekOf = formatISO(monday, { representation: "date" });

export const sampleWeekPlan: WeekPlan = {
  weekOf,
  goals: [
    {
      id: "goal-1",
      text: "Ship the Milestone 1 planning loop with a crisp manual workflow.",
      done: false,
    },
    {
      id: "goal-2",
      text: "Protect two focused strategy blocks for Q2 roadmap decisions.",
      done: false,
    },
    {
      id: "goal-3",
      text: "Keep one wellbeing anchor visible on the plan.",
      done: true,
    },
  ],
  backlog: [
    {
      id: "item-1",
      title: "Draft stakeholder update",
      category: "work",
      type: "stakeholder_update",
      priority: "high",
      duration: 1,
      createdAt: "2026-05-10T09:00:00.000Z",
    },
    {
      id: "item-2",
      title: "Review onboarding notes",
      category: "work",
      type: "review",
      priority: "med",
      duration: 1.5,
      createdAt: "2026-05-10T09:05:00.000Z",
    },
    {
      id: "item-3",
      title: "Book annual health check",
      category: "personal",
      type: "personal",
      priority: "low",
      duration: 0.5,
      createdAt: "2026-05-10T09:10:00.000Z",
    },
    {
      id: "item-4",
      title: "Pick up framing order",
      category: "errands",
      type: "other",
      priority: "med",
      duration: 0.75,
      createdAt: "2026-05-10T09:15:00.000Z",
    },
    {
      id: "item-5",
      title: "Long run planning",
      category: "wellbeing",
      type: "personal",
      priority: "low",
      duration: 1,
      createdAt: "2026-05-10T09:20:00.000Z",
    },
  ],
  blocks: {
    mon: [
      {
        id: "block-1",
        title: "Milestone 1 implementation pass",
        category: "work",
        type: "project",
        priority: "high",
        duration: 3,
        scheduledAt: "2026-05-11",
      },
      {
        id: "block-2",
        title: "Design review notes",
        category: "work",
        type: "review",
        priority: "med",
        duration: 1.5,
        scheduledAt: "2026-05-11",
      },
    ],
    tue: [
      {
        id: "block-3",
        title: "Customer interview synthesis",
        category: "work",
        type: "review",
        priority: "high",
        duration: 2,
        scheduledAt: "2026-05-12",
      },
      {
        id: "block-4",
        title: "Grocery run",
        category: "errands",
        type: "other",
        priority: "low",
        duration: 1,
        scheduledAt: "2026-05-12",
      },
    ],
    wed: [
      {
        id: "block-5",
        title: "Roadmap tradeoff memo",
        category: "work",
        type: "decision",
        priority: "high",
        duration: 3.5,
        scheduledAt: "2026-05-13",
      },
      {
        id: "block-6",
        title: "Follow up with design partners",
        category: "work",
        type: "follow_up",
        priority: "med",
        duration: 1,
        scheduledAt: "2026-05-13",
      },
      {
        id: "block-7",
        title: "Evening reset",
        category: "wellbeing",
        type: "personal",
        priority: "low",
        duration: 1,
        scheduledAt: "2026-05-13",
      },
    ],
    thu: [
      {
        id: "block-8",
        title: "Architecture review prep",
        category: "work",
        type: "meeting_prep",
        priority: "high",
        duration: 2.25,
        scheduledAt: "2026-05-14",
      },
      {
        id: "block-9",
        title: "Quarterly planning workshop",
        category: "work",
        type: "project",
        priority: "high",
        duration: 4.75,
        scheduledAt: "2026-05-14",
      },
    ],
    fri: [
      {
        id: "block-10",
        title: "Weekly review and next actions",
        category: "work",
        type: "review",
        priority: "med",
        duration: 1.5,
        scheduledAt: "2026-05-15",
      },
      {
        id: "block-11",
        title: "Family dinner logistics",
        category: "personal",
        type: "personal",
        priority: "med",
        duration: 1,
        scheduledAt: "2026-05-15",
      },
    ],
  },
};
