import type { Goal, PlanningItem, WeekPlan } from "@/types/planning";

export const mockGoals: Goal[] = [
  {
    id: "goal-1",
    title: "Launch new feature for user authentication",
    description: "Complete the OAuth integration and update user flows",
    priority: "high",
  },
  {
    id: "goal-2",
    title: "Improve dashboard performance",
    description: "Optimize queries and reduce load times by 50%",
    priority: "medium",
  },
  {
    id: "goal-3",
    title: "Strengthen stakeholder relationships",
    description: "Regular check-ins with key partners and decision-makers",
    priority: "medium",
  },
  {
    id: "goal-4",
    title: "Complete Q2 planning",
    description: "Finalize roadmap and resource allocation for next quarter",
    priority: "high",
  },
];

export const mockPlanningItems: PlanningItem[] = [
  {
    id: "item-1",
    title: "Implement OAuth provider integration",
    description: "Add support for Google and GitHub OAuth",
    type: "task",
    source: "linear",
    externalId: "ENG-123",
    externalUrl: "https://linear.app/team/issue/ENG-123",
    status: "In Progress",
    priority: "urgent",
    estimateMinutes: 480,
  },
  {
    id: "item-2",
    title: "Q2 Product Roadmap Review",
    description: "Review and finalize roadmap with leadership team",
    type: "meeting_prep",
    source: "calendar",
    priority: "high",
    estimateMinutes: 120,
    dueDate: "2026-05-12",
  },
  {
    id: "item-3",
    title: "User research synthesis",
    description: "Analyze feedback from last week's interviews",
    type: "review",
    source: "notion",
    priority: "high",
    estimateMinutes: 180,
  },
  {
    id: "item-4",
    title: "Follow up with design team on mockups",
    description: "Review and provide feedback on new dashboard designs",
    type: "follow_up",
    source: "slack",
    priority: "medium",
    estimateMinutes: 60,
  },
  {
    id: "item-5",
    title: "Decide on tech stack for new service",
    description: "Evaluate options and make recommendation",
    type: "decision",
    source: "manual",
    priority: "high",
    estimateMinutes: 90,
    dueDate: "2026-05-15",
  },
  {
    id: "item-6",
    title: "Marketing campaign planning",
    description: "Collaborate on Q3 campaign strategy",
    type: "project",
    source: "manual",
    priority: "medium",
    estimateMinutes: 240,
  },
  {
    id: "item-7",
    title: "Weekly stakeholder update email",
    description: "Send progress update to executive team",
    type: "stakeholder_update",
    source: "email",
    priority: "medium",
    estimateMinutes: 45,
    dueDate: "2026-05-13",
  },
  {
    id: "item-8",
    title: "Code review for PR #234",
    description: "Review authentication changes",
    type: "review",
    source: "github",
    externalId: "234",
    externalUrl: "https://github.com/org/repo/pull/234",
    priority: "high",
    estimateMinutes: 60,
  },
  {
    id: "item-9",
    title: "Professional development: React patterns",
    description: "Complete advanced React course module",
    type: "personal",
    source: "manual",
    priority: "low",
    estimateMinutes: 120,
  },
  {
    id: "item-10",
    title: "Database migration planning",
    description: "Plan migration strategy for new schema",
    type: "task",
    source: "linear",
    externalId: "ENG-125",
    status: "Todo",
    priority: "high",
    estimateMinutes: 180,
  },
];

export const mockWeekPlan: WeekPlan = {
  monday: [
    {
      id: "block-1",
      title: "Q2 Product Roadmap Review prep",
      planningItemId: "item-2",
      estimateMinutes: 120,
      day: "monday",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      id: "block-2",
      title: "Implement OAuth provider integration",
      planningItemId: "item-1",
      estimateMinutes: 240,
      day: "monday",
      startTime: "13:00",
      endTime: "17:00",
    },
  ],
  tuesday: [
    {
      id: "block-3",
      title: "User research synthesis",
      planningItemId: "item-3",
      estimateMinutes: 180,
      day: "tuesday",
      startTime: "09:00",
      endTime: "12:00",
    },
    {
      id: "block-4",
      title: "Follow up with design team",
      planningItemId: "item-4",
      estimateMinutes: 60,
      day: "tuesday",
      startTime: "14:00",
      endTime: "15:00",
    },
    {
      id: "block-5",
      title: "Code review for PR #234",
      planningItemId: "item-8",
      estimateMinutes: 60,
      day: "tuesday",
      startTime: "15:30",
      endTime: "16:30",
    },
  ],
  wednesday: [
    {
      id: "block-6",
      title: "Decide on tech stack for new service",
      planningItemId: "item-5",
      estimateMinutes: 90,
      day: "wednesday",
      startTime: "10:00",
      endTime: "11:30",
    },
    {
      id: "block-7",
      title: "Database migration planning",
      planningItemId: "item-10",
      estimateMinutes: 180,
      day: "wednesday",
      startTime: "13:00",
      endTime: "16:00",
    },
  ],
  thursday: [
    {
      id: "block-8",
      title: "Marketing campaign planning",
      planningItemId: "item-6",
      estimateMinutes: 240,
      day: "thursday",
      startTime: "09:00",
      endTime: "13:00",
    },
    {
      id: "block-9",
      title: "Weekly stakeholder update email",
      planningItemId: "item-7",
      estimateMinutes: 45,
      day: "thursday",
      startTime: "14:00",
      endTime: "14:45",
    },
  ],
  friday: [
    {
      id: "block-10",
      title: "Continue OAuth integration",
      planningItemId: "item-1",
      estimateMinutes: 240,
      day: "friday",
      startTime: "09:00",
      endTime: "13:00",
    },
    {
      id: "block-11",
      title: "Professional development: React patterns",
      planningItemId: "item-9",
      estimateMinutes: 120,
      day: "friday",
      startTime: "14:00",
      endTime: "16:00",
    },
  ],
};
